apiVersion: v1
kind: Service
metadata:
  labels:
    service: prj3-api-feed
  name: prj3-api-feed
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: prj3-api-feed