apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: prj3-reverseproxy
  name: prj3-reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: prj3-reverseproxy
  template:
    metadata:
      labels:
        service: prj3-reverseproxy
    spec:
      containers:
      - image: duypham0909/reverseproxy
        name: prj3-reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            cpu: "150m"
          limits:
            cpu: "500m"
        ports:
        - containerPort: 8080
      restartPolicy: Always